// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VersionClient.Models;

namespace VersionClient.Migrations
{
    [DbContext(typeof(VersionContext))]
    partial class VersionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VersionClient.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UrlLogin")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Versions")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdClient");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("VersionClient.Models.Version", b =>
                {
                    b.Property<int>("IdVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ClientIdClient")
                        .HasColumnType("int");

                    b.HasKey("IdVersion");

                    b.HasIndex("ClientIdClient");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("VersionClient.Models.Version", b =>
                {
                    b.HasOne("VersionClient.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientIdClient");
                });
#pragma warning restore 612, 618
        }
    }
}
