// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VersionClient.Models;

namespace VersionClient.Migrations
{
    [DbContext(typeof(VersionContext))]
    partial class VersionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VersionClient.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdUrlClient")
                        .HasColumnType("int");

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("UrlClientIdUrlClient")
                        .HasColumnType("int");

                    b.HasKey("IdClient");

                    b.HasIndex("UrlClientIdUrlClient");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("VersionClient.Models.UrlClient", b =>
                {
                    b.Property<int>("IdUrlClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdUrlClient");

                    b.ToTable("Version");
                });

            modelBuilder.Entity("VersionClient.Models.Client", b =>
                {
                    b.HasOne("VersionClient.Models.UrlClient", "UrlClient")
                        .WithMany()
                        .HasForeignKey("UrlClientIdUrlClient");
                });
#pragma warning restore 612, 618
        }
    }
}
